export const paths = {
  home: "/",
  bikes: "/bikes",
  bikeDetail: (id: string) => `/bikes/${id}`,
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/forgot-password/reset",
  profile: "/profile",
  myRentals: "/my-rentals",
  rentalCallback: "/rentals/callback",
  contact: "/contact",
  about: "/about",
  admin: "/admin",
  adminBikes: "/admin/bikes",
  adminOrders: "/admin/orders",
  adminUsers: "/admin/users",
  adminSettings: "/admin/settings",
};
